#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Predict Total DV Generated By Different Staged Motors"""
import numpy as np
import astropy.units as u
import matplotlib.pyplot as plt
#custom

"""Python 3.7
   EH Group, Inc. (c) 2019
   Christopher Simpson: christopher.r.simpson@simpsonaerospace.com"""
#------------------------------------------------------------------------------
class motor:
    def __init__(self, Isp, Oxidizer2FuelRatio, OxidizerDensity, FuelDensity, InertMassFraction):
        self.Isp = Isp
        self.rho_o = OxidizerDensity
        self.rho_f = FuelDensity
        self.OF = Oxidizer2FuelRatio
        self.fi = InertMassFraction

class stage(motor):
    def __init__(self, Length, Diameter):
        self.Len = Length
        self.Dia = Diameter
        self.Vol = self.Len*np.pi*(self.Dia/2)**2

class payload:
    def __init__(self, RectangleOrCylinder, Length, Width, Height, Diameter, Mass):
        self.RecOrCyl = RectangleOrCylinder
        self.Len = Length
        self.m = Mass
        if ((self.RecOrCyl is 'Rectangle') or (self.RecOrCyl is 0) or (self.RecOrCyl is 'rec') or (self.RecOrCyl is 'Rec')):
            self.Wid = Width
            self.Hei = Height
            self.Vol = self.Len*self.Wid*self.Hei
        elif ((self.RecOrCyl is 'Circle') or (self.RecOrCyl is 1) or (self.RecOrCyl is 'cir') or (self.RecOrCyl is 'Cir')):
            self.Dia = Diameter
            self.Vol = self.Len*np.pi*(self.Dia/2)**2
